CREATE TABLE CUSTOMER (
	ID INT PRIMARY KEY, -- 숫자형태로 저장되는 아이디
	NAME VARCHAR(20) NOT NULL, -- 문자형태로 저장되는 이름
	ADDRESS VARCHAR(100) -- 문자형태로 저장되는 주소
);

CREATE TABLE ORDERS (
	ORDER_NO INT PRIMARY KEY COMMENT '주문번호', -- 컬럼의 설명
	SALESMAN_ID INT COMMENT '판매자아이디',
	ORDER_DATE DATE NOT NULL COMMENT '주문일자'
);

CREATE TABLE CATEGORIES (
	MENU_ID INT PRIMARY KEY COMMENT '메뉴아이디',
	MENU_NAME CHAR(10) NOT NULL COMMENT '메뉴명',
	KILOCALORIES INT NOT NULL COMMENT '칼로리',
	PRICE INT NOT NULL COMMENT '가격'
);

CREATE TABLE LOCATION (
	LOCATION_ID INT PRIMARY KEY,
	ADDRESS VARCHAR(255) NOT NULL,
	POSTAL_CODE VARCHAR(20),
	CITY VARCHAR(50)
);

CREATE TABLE MENUS (
	MENU_ID INT PRIMARY KEY COMMENT '메뉴아이디',
	MENU_NAME CHAR(10) NOT NULL COMMENT '메뉴명',
	KILOCALORIES INT NOT NULL COMMENT '칼로리',
	PRICE INT NOT NULL COMMENT '가격'
);

CREATE TABLE CURRICULUM (
	NO INT PRIMARY KEY COMMENT '과목번호',
	NAME VARCHAR(30) COMMENT '과목명',
	POINTS INT COMMENT '학점',
	PROFID INT COMMENT '교수 번호'
);

CREATE TABLE DEPT (
	DEPT_NO INT PRIMARY KEY COMMENT '부서번호',
	DEPT_NAME VARCHAR(20) COMMENT '부서명',
	DEPT_LOC VARCHAR(20) COMMENT '부서위치'
);

CREATE TABLE EMP (
	EMP_NO INT PRIMARY KEY,
	DEPT_NO INT,
	EMP_NAME VARCHAR(10),
	HDATE DATE
);

CREATE TABLE CINEMA (
	THEATER_NO INT PRIMARY KEY COMMENT '상영관번호',
	LOCATION VARCHAR(100) COMMENT '위치',
	TEL VARCHAR(50) COMMENT '전화번호'
);

CREATE TABLE RESERVATION (
	THEATER_NO INT NOT NULL,
	MOVIE_NAME VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	SEAT_NO INT,
	DATE DATE,
	PRICE INT
);
