ALTER TABLE CUSTOMER ADD GENDER VARCHAR(9);

ALTER TABLE CUSTOMER MODIFY GENDER VARCHAR(100);
ALTER TABLE CUSTOMER MODIFY GENDER INT NOT NULL;
ALTER TABLE CUSTOMER MODIFY GENDER INT NOT NULL COMMENT '성별';

-- 컬럼의 이름은 MODIFY로 변경이 안됨

-- 이름만 변경할 때 사용
ALTER TABLE CUSTOMER RENAME COLUMN GENDER TO GEN;

-- 이름과 다른 옵션을 한번에 변경할 때 사용
ALTER TABLE CUSTOMER CHANGE COLUMN GEN GENDER VARCHAR(9);

-- 이름, 주소, 성별 컬럼 삭제
ALTER TABLE CUSTOMER DROP COLUMN NAME;
ALTER TABLE CUSTOMER DROP COLUMN ADDRESS;
ALTER TABLE CUSTOMER DROP COLUMN GENDER;

ALTER TABLE CUSTOMER ADD NAME VARCHAR(20) NOT NULL;
ALTER TABLE CUSTOMER ADD ADDRESS VARCHAR(100);
ALTER TABLE CUSTOMER ADD GENDER VARCHAR(9);

ALTER TABLE ORDERS ADD COLUMN SALESMAN_ID INT COMMENT '판매자아이디';
ALTER TABLE ORDERS RENAME COLUMN SALESMAN_ID TO SALESMAN_NAME;

ALTER TABLE LOCATION MODIFY LOCATION_ID INT COMMENT '위치번호';
ALTER TABLE LOCATION MODIFY ADDRESS VARCHAR(255) NOT NULL COMMENT '주소';
ALTER TABLE LOCATION MODIFY POSTAL_CODE VARCHAR(20) COMMENT '우편번호';
ALTER TABLE LOCATION MODIFY CITY VARCHAR(50) COMMENT '도시명';

ALTER TABLE CURRICULUM CHANGE COLUMN NO CURRICULUM_NO INT COMMENT '과목번호';
ALTER TABLE CURRICULUM RENAME COLUMN NO TO CURRICULUM_NO;
ALTER TABLE CURRICULUM CHANGE COLUMN NAME CURRICULUM_NAME VARCHAR(30) NOT NULL COMMENT '과목명';
ALTER TABLE CURRICULUM CHANGE COLUMN POINTS CURRICULUM_POINTS INT NOT NULL COMMENT '학점';
ALTER TABLE CURRICULUM CHANGE COLUMN PROFID CURRICULUM_PROFID INT NOT NULL COMMENT '교수 번호';

ALTER TABLE EMP MODIFY EMP_NO INT COMMENT '직원번호';
ALTER TABLE EMP MODIFY DEPT_NO INT COMMENT '부서번호';
ALTER TABLE EMP MODIFY EMP_NAME VARCHAR(10) COMMENT '직원이름';
ALTER TABLE EMP MODIFY HDATE DATE COMMENT '입사일';
ALTER TABLE EMP ADD COLUMN SALARY INT NOT NULL COMMENT '월급';






