DELETE
FROM CUSTOMER
WHERE ADDRESS = '제주도';

DELETE
FROM CUSTOMER;

INSERT INTO CUSTOMER (NAME, ADDRESS)
VALUES ('둘리', '서울');

-- 회원 테이블의 모든 데이터 삭제, 회원번호 리셋
TRUNCATE CUSTOMER;

-- Q1
DELETE FROM BOOK WHERE PUB_DATE IN ('2023-01-01', '2023-02-01');

-- Q2
DELETE FROM CONTACTS WHERE EMAIL LIKE '%@naver.com%' AND PHONE IS NULL;

-- Q3
DELETE FROM GIFT WHERE NAME LIKE '%세트' AND PRICE <= 20000;

-- Q4
DELETE FROM CLASS WHERE CLASS_TIME > 100000;

-- Q5
DELETE FROM RESERVATION WHERE SEAT_NO LIKE 'A%' AND MOVIE_NAME = '아바타';

-- Q6
DELETE FROM PRODUCT WHERE PRODUCT_NO IN (2,4,6);









