/* 숫자 함수 */

-- 반올림, 올림, 내림
SELECT ROUND(1.4), CEIL (1.4), FLOOR(1.4);

-- 목록 중에서 가장 큰 값, 가장 작은 값
SELECT GREATEST(1, 2, 3), LEAST(1, 2, 3);

-- 절대값
SELECT ABS(1), ABS(-1);

-- 소수점자리 선택
SELECT TRUNCATE(1.2345, 2);

/* 논리 함수 */

-- 컬럼이 NULL이면 ''으로 치환
SELECT NAME, IFNULL(ADDRESS, '없음')
FROM CUSTOMER;

/* 문자열 함수 */

-- 대문자로 변환
SELECT UPPER('abc'); 

-- 소문자로 변환
SELECT LOWER('ABC'); 

-- 문자열 연결하기
SELECT CONCAT('ab', 'cd', 'e'); 

-- 문자열 자르기
SELECT SUBSTR ('ABCDEFG', 3), SUBSTR('ABCDEFG', 3, 2); 

-- 문자열 자르기
SELECT LEFT ('ABCDEFG', 3), RIGHT('ABCDEFG', 3);

-- 문자열 길이 구하기 (바이트크기, 자리수)
SELECT LENGTH ('ABCDE'), CHAR_LENGTH('ABCDE'); 

-- 문자열 길이 구하기 (바이트크기, 자리수)
SELECT LENGTH ('안녕하세요'), CHAR_LENGTH('안녕하세요'); 

-- 공백 제거하기
SELECT TRIM(' HELLO ');

-- 특정 문자로 자리 체우기
SELECT LPAD('ABC', 5, '*'), RPAD('ABC', 5, '-');

-- 문자 교체하기
SELECT REPLACE ('오늘은 월요일 입니다', '월요일 ', '수요일');

-- 품목을 그룹으로 묶기
SELECT TYPE
FROM GIFT
GROUP BY TYPE;

-- 최소값, 최대값, 행의 개수, 합계, 평균
SELECT MIN(PRICE), MAX(PRICE), COUNT(*), SUM(PRICE), AVG(PRICE)
FROM GIFT;

SELECT TYPE, MIN(PRICE), MAX(PRICE), COUNT(*), SUM(PRICE), AVG(PRICE)
FROM GIFT
GROUP BY TYPE;

-- 품목별로 선물목록 구하기
SELECT TYPE, GROUP_CONCAT(NAME)
FROM GIFT
GROUP BY TYPE;

-- Q1
SELECT ADDRESS AS '지역', COUNT(*) AS '회원의 수'
FROM CUSTOMER
GROUP BY ADDRESS;

-- Q2
SELECT ADDRESS AS '지역', GROUP_CONCAT(NAME) AS '회원목록'
FROM CUSTOMER
GROUP BY ADDRESS;

-- Q3
SELECT PUBLISHER AS '출판사', COUNT(*) AS '개수', SUM(PRICE) AS '합계'
FROM BOOK
GROUP BY PUBLISHER;

-- Q4
SELECT CONCAT(MONTH(PUB_DATE), '월') AS '월', COUNT(*) AS '출판된 책의 개수'
FROM BOOK
GROUP BY MONTH(PUB_DATE);

-- Q5
SELECT LAST_NAME, FIRST_NAME , CONCAT(LAST_NAME, FIRST_NAME) AS 'FULL_NAME'
FROM CONTACTS;

-- Q6
SELECT LAST_NAME AS '성' , COUNT(*) AS '사람의 수'
FROM CONTACTS
GROUP BY LAST_NAME;

-- Q7
SELECT `DATE` AS '날짜', MOVIE_NAME AS '영화명', COUNT(*) AS '예매건수'
FROM RESERVATION
GROUP BY DATE, MOVIE_NAME;

-- Q8
SELECT CONCAT(LEFT (SEAT_NO , 1), '열') AS '자리' , GROUP_CONCAT(USER_NAME) AS '명단'
FROM RESERVATION
GROUP BY LEFT (SEAT_NO , 1);

-- Q9
SELECT CATEGORY AS '카테고리', MAX(PRICE) AS '최고가'
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY MAX(PRICE) DESC;

-- Q10
SELECT CATEGORY AS '카테고리', GROUP_CONCAT(PRODUCT_NAME) AS '제품리스트', SUM(PRICE) AS '합계'
FROM PRODUCT
GROUP BY CATEGORY;












