-- 직원테이블에서 부서가 인사부인 직원 조회
CREATE VIEW emp_view1 AS
SELECT EMP_NO, EMP_NAME, DEPT_NO
FROM EMP
WHERE DEPT_NO = 1;

-- 진짜 테이블에 데이터를 추가하면, 뷰도 변경됨
INSERT INTO EMP VALUES
(1011, '둘리', 1, '인천 연수구 송도동', 330, 20240801);

-- 가상테이블은 데이터가 반영이 되기 때문에, 조회를 다시할 필요가 없다.

-- 뷰 조회
SELECT * FROM EMP_VIEW1;

-- 뷰 수정하기
ALTER VIEW emp_view1 AS
SELECT EMP_NO, EMP_NAME, DEPT_NO
FROM EMP
WHERE DEPT_NO = 1;

-- 일반 테이블처럼 데이터 수정, 삭제 가능. 원본 데이터에도 영향 있음
UPDATE EMP_VIEW1 
SET DEPT_NO = 3
WHERE EMP_NO = 1011;

-- 뷰 삭제
DROP VIEW EMP_VIEW1;



-- Q1
CREATE VIEW EMP_VIEW2 AS
SELECT E.EMP_NO, E.EMP_NAME, D.DEPT_NAME
FROM EMP E 
JOIN DEPT D 
ON
E.DEPT_NO = D.DEPT_NO
WHERE D.DEPT_NO = 1;

-- Q2
CREATE VIEW EMP_VIEW3 AS
SELECT D.DEPT_NO AS '부서번호', D.DEPT_NAME AS '부서명', GROUP_CONCAT(E.EMP_NAME) AS '사원리스트', COUNT(*) AS '인원' 
FROM EMP E 
JOIN DEPT D 
ON
E.DEPT_NO = D.DEPT_NO
GROUP BY D.DEPT_NO ;

-- Q3
CREATE VIEW EMP_VIEW4 AS
SELECT D.DEPT_NAME AS '부서명', MIN(E.SALARY)AS '최소급여', MAX(E.SALARY)AS '최대급여', ROUND(AVG(E.SALARY))AS '평균급여'
FROM EMP E 
JOIN DEPT D 
ON
E.DEPT_NO = D.DEPT_NO
GROUP BY D.DEPT_NO ;

-- Q4
CREATE VIEW EMP_VIEW5 AS
SELECT EMP_NO , EMP_NAME , SALARY 
FROM EMP 
WHERE EMP_NAME LIKE '김%'
ORDER BY SALARY DESC, EMP_NAME
LIMIT 3;

INSERT INTO EMP VALUES
(1012, '김사부', 2, '인천 연수구 송도동', 400, 20240803);














